version: '3.8'

services:
  monitoring:
    container_name: signalcartel-monitoring
    build:
      context: ../..
      dockerfile: containers/monitoring/Dockerfile
    environment:
      - NODE_ENV=production
      - NODE_OPTIONS=--max-old-space-size=512
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}
      - LOG_DIR=/app
    volumes:
      - monitoring-logs:/app/logs
      - ../../.env.local:/app/.env.local:ro
      - ../../monitoring:/app/monitoring:ro
      - monitoring-data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "pgrep", "-f", "resource-monitor"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "5"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          memory: 256M
    networks:
      - signalcartel-network

  # Prometheus for metrics collection
  prometheus:
    image: prom/prometheus:latest
    container_name: signalcartel-prometheus
    restart: unless-stopped
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - signalcartel-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:latest
    container_name: signalcartel-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_PASSWORD:-admin}
    volumes:
      - grafana-data:/var/lib/grafana
    networks:
      - signalcartel-network

volumes:
  monitoring-logs:
    driver: local
  monitoring-data:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local

networks:
  signalcartel-network:
    external: true
    name: signalcartel_signalcartel-network