route:
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 1h
  receiver: 'default'
  routes:
  - match:
      severity: critical
      service: signalcartel
    receiver: signalcartel-critical
    repeat_interval: 30m
  - match:
      service: signalcartel
    receiver: signalcartel-all
    repeat_interval: 1h

receivers:
- name: 'default'
  
- name: 'signalcartel-critical'
  email_configs:
  - to: ['test@example.com']
    subject: '🚨 CRITICAL: SignalCartel Alert'
    body: |
      {{ range .Alerts }}
      {{ .Annotations.title }}
      
      {{ .Annotations.description }}
      
      Action: {{ .Annotations.action }}
      
      Time: {{ .StartsAt }}
      {{ end }}

- name: 'signalcartel-all'
  email_configs:
  - to: ['test@example.com']
    subject: 'SignalCartel Alert: {{ .GroupLabels.alertname }}'
    body: |
      {{ range .Alerts }}
      {{ .Annotations.title }}
      
      {{ .Annotations.description }}
      
      Action: {{ .Annotations.action }}
      
      Time: {{ .StartsAt }}
      {{ end }}
